[
    'Omron/欧姆龙', 'LUNASOL/日月晶采', 'OMI/近江兄弟', '城野医生', '丸美屋', 'ALOINS',
    "KIEHL'S/科颜氏", 'Freeplus', '香奈儿', 'Msh-Labo', 'GATSBY/杰士派', 'NOLIE',
    'Rilakkuma/轻松小熊', 'Marlboro/万宝路', 'REVLON/露华浓', 'Armani Beauty',
    'Sloggi/黛安芬', 'VENUS SPA', 'PANDORA/潘多拉', 'PDC/碧迪皙', 'LuLuLun', 'Gucci',
    'Kose/高丝', 'ACSEINE/雅倩美', 'UNICHARM/尤妮佳', 'BARBER PRO', 'MELTY BERRY',
    'Fracora', 'RAFRA', 'The Ginza', 'Avène', 'LA MER/海蓝之谜', 'Pigeon/贝亲',
    'DECORTE/黛珂', '纪梵希', 'Dr. Jart+', 'CEZANNE/倩丽', '陶陶酒本舗', 'Sana/莎娜',
    'Adidas/阿迪达斯', 'Curel/珂润', 'Dior/迪奥', 'COSME NIPPON', 'ELIXIR WHITE ',
    'Spa treatment', '兰蔻', 'LAB SERIES/朗仕', 'BOBBI BROWN', 'Meiji/明治', '黑龙堂',
    'COVERMARK', 'Creer Beaute/凡尔赛', 'Elixir/怡丽丝尔', 'La Mer', 'MAC', 'DHC/蝶翠诗',
    'CITEETH WHITE', 'Nintendo/任天堂', 'ASAHI LABO/旭研究所', 'Flowfushi/熊野职人',
    'BABY COLOR', 'DENTISTE', 'CLEVERIN/大幸药品', 'IPSA', 'BeBe-Pro',
    'Moist Labo', 'Quality first/皇后的秘密', '米田药品', 'Shiseido/资生堂', 'MDNA',
    'Kracie/肌美精', 'MUJI/无印良品', 'SS制药', 'KIRIBAI', 'Fujiko', 'Sofina/苏菲娜',
    'Fancl/芳珂', 'Apple', 'IQOS', 'ALBION', 'VEET/薇婷', 'HOLLYWOOD',
    'AQUA SAVON', 'Hada Labo/肌研', 'NATURALI', 'POLA', 'ISHIZAWA LABS/石泽研究所',
    'DECORTE', 'La prairie/莱珀妮', 'THREE', 'WaKoDo/和光堂', 'CLINIQUE', '阿曼尼',
    'TF', '鬼冢虎', 'Dior', '一心堂本铺', 'NARS', 'KOBAYASHI/小林制药', 'MEDIHEAL/美迪惠尔',
    'Kao/花王', 'SHISEIDO', '雅诗兰黛', 'Guerlain/娇兰', 'Hisamitsu/久光制药', 'HACCI',
    'BIODERMA/贝德玛', 'Canmake/井田', 'Bobbi Brown', 'Elégance', 'POLA/宝丽',
    'IPSA/茵芙莎', 'RMK', 'SUQQU', 'Estee Lauder', 'LANCOME/兰蔻', "L'OREAL/欧莱雅",
    '米美糀', '菊正宗', 'Givenchy', 'Elégance/雅莉格丝', 'SOFINA', 'MAC/魅可', '第一三共制药',
    'ETTUSAIS/艾杜纱', 'SISLEY/希思黎', 'AISHODO/爱妆堂', 'Freeplus/芙丽芳丝', '惠之本铺',
    'Dyson/戴森', 'Clarins', 'HABA/无添加主义', 'CHANEL/香奈儿', 'Utena/佑天兰', 'CLARINS',
    'CPB/肌肤之钥', 'HR/赫莲娜', 'MAYBELLINE美宝莲', 'LB Cosmetics', 'Royce’',
    'SKII/SK2', 'YSL/Yves Saint Laurent', 'IT Cosmetics', 'YSL/圣罗兰', '川久保玲',
    'BIOTHERM', 'NIKE/耐克', 'TOM FORD', 'DR.CI.LABO/ 城野医生', 'Tom Ford', '三宅一生',
    'Estée Lauder', '龙角散', 'Versace', 'Sekkisei/雪肌精', 'ROHTO/乐敦', 'MANDOM/曼丹',
    "Kiehl's/科颜氏", 'Attenir/艾天然', 'CHANEL', 'HABA', 'Gucci ', 'SHU UEMURA/植村秀',
    'ROYAL', 'Shiseido', 'CPB', 'FANCL', 'ALOVIVI', 'Champion/冠军',
    'OKAMOTO/冈本', 'Lancôme', 'ReFa', 'EXCEL', 'RECOVER', 'GUERLAIN',
    'ALBION/澳尔滨', 'COSMOBEAUTY', 'Guerlain', 'SUNSTAR', 'Mellsavon',
    'COVERMARK/傲丽', 'LIPSTICK', 'KANEBO/嘉娜宝', 'Axxzia/晓姿', 'Armani/阿玛尼',
    'Tiffany&Co./蒂芙尼', 'VAPE/未来', 'DR.JOU/森田药妆', '理肤泉', 'Reveur', '和汉堂',
    'GUCCI/古驰', 'Miu Miu', 'ANNA SUI/安娜苏'
]